name: arank_india
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.12.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^4.0.0
  firebase_auth: ^6.0.0
  cloud_firestore: ^6.0.0
  firebase_storage: ^13.0.0
  pinput: ^5.0.1
  provider: ^6.1.5
  google_fonts: ^6.3.0
  flutter_animate: ^4.5.2
  cached_network_image: ^3.4.1
  lottie: ^3.3.1
  flutter_svg: ^2.2.0
  shared_preferences: ^2.5.3
  connectivity_plus: ^7.0.0
  url_launcher: ^6.3.0
  intl: ^0.20.2
  uuid: ^4.5.1
  pdf: ^3.11.0
  printing: ^5.13.4
  path_provider: ^2.1.5
  open_filex: ^4.5.0
  qr_flutter: ^4.1.0
  share_plus: ^10.0.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  carousel_slider: ^5.1.1

dev_dependencies:
  flutter_launcher_icons: ^0.14.4
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_native_splash: ^2.4.1

flutter_native_splash:
  color: "#FFFFFF"
  image: assets/images/logos/logo.png
  android: true
  ios: true
  android_12:
    color: "#FFFFFF"
    image: assets/images/logos/logo.png

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/logos/logo.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/logos/
    - assets/images/icons/
    - assets/images/backgrounds/
    - assets/images/banners/
    - assets/images/avatars/
    - assets/images/home_cards/
    - assets/animations/
    - assets/animations/lottie/
    - assets/animations/rive/
    - assets/fonts/
    - assets/audio/
    - assets/videos/
    - assets/pdf/
    - assets/json/
    - assets/avatars/
